<?php

namespace AppBundle\Repository;


/**
 * ProductOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\Entity\User;

class ProductOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function countOrdersWithStatus($status)
    {
        return $this->createQueryBuilder("o")
            ->select("count(o.id)")
            ->where("o.status = :status")
            ->setParameter("status", $status)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param $user User
     * @param $status
     * @return mixed
     */
    public function getOrdersForUserWithStatus($user, $status)
    {
        return $this->createQueryBuilder("o")
            ->select("o")
            ->where("o.status = :status")
            ->andWhere("o.user = :user")
            ->setParameter("user", $user->getId())
            ->setParameter("status", $status)
            ->getQuery()
            ->getResult();

    }
    public function getPaginationQueryByStatus($status)
    {
        return $this->createQueryBuilder("o")
            ->select("o")
            ->join("o.user","u")
            ->where("o.status = :status")
            ->setParameter("status",$status)
            ->getQuery();
    }
}
