<?php

namespace AppBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveDESC()
    {
        $now = new \DateTime();
       return $this->createQueryBuilder("p")
            ->select("p")
            ->where("p.startsOn <= :date")
            ->andWhere("p.endsOn >= :date")
            ->setParameter("date",$now)
            ->orderBy("p.percentage","DESC")
            ->getQuery()->getResult();
    }
}
