<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Promotion;
use Doctrine\ORM\EntityRepository;


/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    public function findAllActiveDESC()
    {
        $now = new \DateTime();
        return $this->createQueryBuilder("p")
            ->select("p")
            ->where("p.startsOn <= :date")
            ->andWhere("p.endsOn >= :date")
            ->setParameter("date", $now)
            ->orderBy("p.percentage", "DESC")
            ->getQuery()->getResult();
    }

    /**
     * @return Promotion[]
     */
    public function findAllNotExpiredDESC()
    {
        $now = new \DateTime();
        return $this->createQueryBuilder("p")
            ->select("p")
            ->where("p.endsOn >= :date")
            ->setParameter("date", $now)
            ->orderBy("p.percentage", "DESC")
            ->getQuery()->getResult();

    }

}
