<?php

namespace AppBundle\Repository;

/**
 * SizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeRepository extends \Doctrine\ORM\EntityRepository
{
}
