<?php

namespace AppBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class UserRepository extends EntityRepository
{
    public function findByUserNameOrFullName($user)
    {
        $qb=$this->createQueryBuilder("u");
        return $qb
            ->select("u")
            ->add('where', $qb->expr()->orX(
                $qb->expr()->eq('u.username', ":user"),
                $qb->expr()->eq('u.fullName', ":user")
            ))
            ->setParameter("user",$user)
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }
}
