app:
    resource: "@AppBundle/Controller"
    type:   annotation
    prefix:   /{_locale}
    requirements:
       _locale: "[a-z]{2}"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:  /{_locale}
