security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN:      [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /%locale%/login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: homepage


            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

            remember_me:
                secret: secret
                lifetime: 604800 # 7 days in seconds
                path:     /
                domain: ~
    access_control:

        - { path: ^/%locale%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/register, role: IS_AUTHENTICATED_ANONYMOUSLY   }
        - { path: ^/%locale%/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/admin, role: ROLE_ADMIN }