# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    demo_user.registration_listener:
        class: AppBundle\EventListeners\AddDefaultRoleListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.promotion:
       class:     AppBundle\Services\PromotionService
       arguments: []

    app.image_uploader:
       class: AppBundle\Services\ImageUploaderService
       arguments: ['%images_directory%','%images_view_directory%']