# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.mailer_service:
        class: AppBundle\Services\AppMailerService
        arguments: ["@mailer","@translator","@templating"]

    app.promotion:
       class:     AppBundle\Services\PromotionService
       arguments: ['@doctrine.orm.entity_manager']

    app.aggregator:
       class:     AppBundle\Services\ArrayAggregatorService
       arguments: ['@app.promotion', '@doctrine.orm.entity_manager']

    app.image_uploader:
       class: AppBundle\Services\ImageUploaderService
       arguments: ['%images_directory%','%images_view_directory%',"@doctrine.orm.entity_manager"]

    app.custom_user_manipulator:
       class: AppBundle\Services\CustomUserManipulator
       arguments: ["@doctrine.orm.entity_manager", "@fos_user.user_manager", "@security.password_encoder"]